import pytest
from onthisday.event import Event


@pytest.fixture
def body():
    with open("sources/accadde_oggi/accadde_oggi.html") as f:
        return f.read()


@pytest.fixture
def events():
    return [
        Event(1604, "Debutta al Whitehall Palace di Londra la tragedia “Otello” di William Shakespeare."),
        Event(1611,
              "A sette anni dal debutto di “Otello” il Whitehall Palace presenta un nuovo lavoro di William Shakespeare tenendo a battesimo “La tempesta”."),
        Event(1755,
              "Un terremoto di intensità stimata in magnitudo 8,5 durato circa sei minuti distrugge oltre la metà della capitale del Portogallo. Il numero di morti a Lisbona è valutato in circa cinquantamila persone ma secondo altre rilevazioni sarebbero più del doppio."),
        Event(1765,
              "Entra in vigore lo Stamp Act con cui oltre al pagamento di una tassa le colonie americane sono obbligate a stampare documenti e giornali su carta legale bollata prodotta a Londra. La legge approvata a marzo serve a finanziare l’esercito britannico in Nord America."),
        Event(1884,
              "La Conferenza Internazionale dei Meridiani si chiude a Washington con nuove regole sull’orientamento tramite coordinate di latitudine e longitudine. E’ stato varato (il 13 ottobre con risoluzione approvata il 22) anche il nuovo sistema di fusi orari che suddivide la Terra in ventiquattro aree partendo dal meridiano dell’osservatorio di Greenwich."),
        Event(1894,
              "Il microbiologo e infettivologo francese Emile Roux annuncia al Congresso medico di Budapest la messa a punto di una sieroterapia contro la difterite, una delle principali cause di mortalità infantile, la cui tossina aveva identificato con Alexandre Yersin nel 1889."),
        Event(1896,
              "Fondato a Bologna il giornale “L’Avvenire d’Italia” nato da un progetto di Giovanni Acquaderni e Giovanni Grosoli che pensavano a un quotidiano di ispirazione cattolica. Sotto la direzione di Filippo Crispolti il primo numero del giornale arriva in edicola con il sottotitolo: “Giornale quotidiano delle Romagne e dell’Emilia”."),
        Event(1897,
              "Su iniziativa di un gruppo di studenti del liceo classico Massimo d’Azeglio che si ritrova in corso Re Umberto, viene fondato a Torino lo Sport Club Juventus."),
        Event(1902,
              "Italia e Francia raggiungono un accordo in base al quale il governo di Roma si impegna a rimanere neutrale nel caso in cui la Francia dovesse subire un attacco. Lo scambio di lettere tra il ministro degli esteri Giulio Prinetti e l’ambasciatore di Francia Camille Barrere (avvenuto in giugno e postdatato) mira a neutralizzare gli accordi della Triplice Intesa."),
        Event(1913,
              "Entra in vigore sull’intero territorio italiano la riforma giudiziaria che istituisce il ruolo del “giudice unico” nei tribunali. La modifica è stata introdotta dalla legge reale 1311 del 19 dicembre 1912."),
        Event(1922,
              "Spodestato Mehmet VI Vahdettina da parte dell’Assemblea nazionale turca, nel paese viene abolito ufficialmente il sultanato dell’Impero ottomano. La Turchia si prepara a dare vita al nuovo ordinamento repubblicano guidata da Mustafa Kemal."),
        Event(1950,
              "Due nazionalisti portoricani tentano di assassinare il presidente statunitense Harry Truman nella sua residenza di Blair House a Washington. L’attentato fallisce ma nell’azione feriscono due guardie e ne uccidono una terza, Leslie Coffelt che rispondendo al fuoco uccide Griselio Torresola. Il complice Oscar Collazo ferito al petto viene arrestato."),
        Event(1954,
              "Con una serie di attacchi alle istituzioni nazionali esplode la rivolta algerina al colonialismo francese e prende vita il Fronte di Liberazione Nazionale i cui capi storici sono: Bitat, Boulaïd, Mourad, Boudiaf, Belkacem e M’Hidi. I primi obiettivi di una guerra che durerà otto anni sono installazioni militari, magazzini, posti di polizia e mezzi di comunicazione."),
        Event(1956,
              "A Grazzano Monferrato muore Pietro Badoglio, il generale e politico artefice dell’alleanza italiana con gli Stati Uniti durante la seconda guerra mondiale contro le forze naziste. L’ex presidente del Consiglio dei Ministri del Regno d’Italia aveva 85 anni."),
        Event(1962, "La Grecia entra a far parte del Mercato Comune Europeo."),
        Event(1962,
              "Viene pubblicato “Il re del terrore” il primo numero del fumetto Diabolik ideato e realizzato da Angela e Luciana Giussani che per l’occasione hanno anche inventato il nuovo formato tascabile da 12×17 centimetri."),
        Event(1964,
              "Alle 10.41 il sindaco Pietro Bucalossi inaugura a Milano il primo tratto della metropolitana. Attraverso ventuno stazioni collega la zona nord della città al confine con Sesto San Giovanni, con piazzale Lorenzo Lotto a poca distanza dallo stadio di San Siro."),
        Event(1968,
              "Il primo album solista di un componente dei Beatles è di George Harrison. Viene pubblicato oggi il disco colonna sonora “Wonderwall music” su etichetta Apple, la stessa per la quale incidono i quattro di Liverpool."),
        Event(1969,
              "Arriva in edicola il primo numero del settimanale Lotta Continua. Il giornale, organo di stampa ufficiale dell’omonima formazione extraparlamentare, è diretto dal critico e scrittore Piergiorgio Bellocchio."),
        Event(1973,
              "Nuovo primato in chirurgia: a Bari il prof. Giuseppe Marinaccio realizza un trapianto di rene da donatore vivente in mezz’ora. Il paziente è in ottime condizioni."),
        Event(1981, "Lo stato caraibico di Antigua e Barbuda diventa indipendente dal Regno Unito."),
        Event(1989, "La Germania Est riapre i propri confini con la Cecoslovacchia."),
        Event(1990,
              "Indennizzo da 100 dollari per Sandra Miller la ventiseienne oggetto di insulti, proposte sessuali e carezze al seno da parte di Mike Tyson due anni prima in una discoteca. La giuria del tribunale riconosce il pugile colpevole di abuso ma non di violenza."),
        Event(1993,
              "Entra in vigore il trattato di Maastricht che fissa le modalità di creazione dell’Europa Unita. Prevede l’integrazione economica, politica e sociale dei paesi che aderiscono all’Unione."),
        Event(1994,
              "Pietro Pacciani viene ritenuto responsabile di quattordici dei sedici duplici omicidi attribuiti al “Mostro di Firenze” e condannato all’ergastolo in primo grado dal Tribunale di Firenze."),
        Event(1997,
              "In occasione del Tokyo Film festival viene presentato in prima visione mondiale il film “Titanic” di James Cameron con Leonardo di Caprio e Kate Winslet. Quello che si preannuncia come il colossal di maggior successo dell’epoca uscirà ufficialmente negli Stati Uniti il 19 dicembre e in Italia il prossimo 16 gennaio."),
        Event(1998,
              "Con l’attuazione del protocollo 11 diventa permanente la Corte Europea dei Diritti dell’Uomo istituita nel 1950 dalla Convenzione Europea per la salvaguardia dell’Uomo e delle Libertà Fondamentali. La corte era attiva dal 1959 con una modalità operativa differente che coinvolgeva tre diverse istituzioni."),
        Event(2001,
              "La squadra femminile di fioretto composta da Giovanna Trillini, Valentina Vezzali, Diana Bianchedi e Frida Scarpa, vince l’oro ai mondiali di scherma di Nimes in Francia."),
        Event(2002,
              "La società italiana Schemaventotto che fa capo al gruppo Benetton lancia un’offerta pubblica di acquisto volontaria totalitaria su Autostrade Spa del valore di quasi otto miliardi di euro."),
        Event(2007,
              "A Monaco di Baviera si apre la quattordicesima edizione degli MTV Europe Music Awards. La manifestazione musicale è presentata da Snoop Dogg."),
        Event(2007,
              "L’italiano Paolo Bettini riceve per la quarta volta il Giglio d’Oro come miglior ciclista professionista dell’anno."),
        Event(2009,
              "Si spegne a Milano la poetessa Alda Merini. Da tempo malata aveva compiuto settantotto anni lo scorso mese di marzo."),
        Event(2010,
              "La Repubblica Popolare Cinese annuncia l'avvio del suo sesto censimento generale. Si stima un aumento più contenuto della popolazione rispetto all'ultimo censimento di 10 anni fa in cui si era registrato un incremento dell'11,7%."),
        Event(2011,
              "L’italiano Mario Draghi assume la carica di presidente della Banca Centrale Europea. Era stato designato al ruolo lo scorso 24 giugno per sostituire, alla scadenza del mandato di otto anni, il predecessore Jean Claude Trichet."),
        Event(2012,
              "In base ai dati diffusi in giornata Gmail, il servizio di posta elettronica gratuito lanciato nel 2004 da Google, con quattrocentoventicinque milioni di utenti attivi è il più popolare del web seguito in seconda posizione da Hotmail e in terza Yahoo mail."),
        Event(2018,
              "La Repubblica di Palau è il primo stato al mondo a bandire creme solari e altri prodotti per la cura della pelle realizzati con specifici prodotti chimici. La legge, che entrerà in vigore nel 2020 con multe fino a 1000 dollari, è volta a proteggere le vulnerabili barriere coralline del paese."),
        Event(2019,
              "La ex ministro delle finanze francese Christine Lagarde dopo essere stata la prima donna alla guida del Fondo Monetario Internazionale, diventa anche la prima donna presidente della Banca Centrale Europea. Assume la carica a cui era stata designata nel luglio scorso approvata dal Parlamento Europeo in settembre.")
    ]
